try{

    console.log('se esta ejecutando bien')
    const doble = miFuncion(num)
    console.log(doble)
}catch(e){
   
    console.log('error')
}
finally{
    console.log('se ejectua haya error o no')
}